name: FraithorAuctions
api-version: 1.13
authors:
  - Fraithor
  - RonanCraft
version: ${project.version}
main: com.fraithor.fraithorauctions.FraithorAuctions

commands:
  fraithorauctions:
    description: Open auctions GUI
    aliases:
      - fa
      - fauctions
      - auctions
      - ah
      - auction
      - auctionhouse
      - auctionh
      - ahouse

permissions:

  fraithorauctions:
    description: Main permission
    default: op

  fraithorauctions.view:
    description: Permission to view GUI

  fraithorauctions.bid:
    description: Permission to place bid

  fraithorauctions.create:
    description: Permission to create auctions